"""Validation of caller-supplied values that get spliced into server-built BigQuery SQL.

The db-api `/query` endpoint accepts a SQL string and nothing else — its request body is
`{sql, max_rows, dry_run}` — so there is no parameter-binding channel to bind a value to.
Validation at this boundary is therefore the only place a value can be checked, and this
module is the single place it happens.

The approach is an allow-list, not escaping: a value is accepted only if every character
is in a set that cannot terminate a BigQuery string literal or start a new token. Quote
characters (`'`, `"`, backtick), the escape character (backslash), the statement separator
(`;`), whitespace, comment starters and parentheses are all outside the allowed set, so an
accepted value cannot break out of the literal it is placed in. Numeric arguments never
travel as strings at all: they are coerced through int()/float() and range-checked, so the
rendered token is generated by Python's own repr of a number.

This is stdlib-only and imports nothing from the rest of the package, so both the tool
executor and the SDK can depend on it.
"""

import math
import re

__all__ = [
    "SqlValueError",
    "normalize_literal",
    "quote_literal",
    "quote_literal_list",
    "sql_float",
    "sql_int",
]

# gene symbols, resource ids, dataset ids, cell types. Deliberately excludes ' " ` \ ;
# whitespace, parentheses, comma, * and the comment starters - the characters an injected
# value would need to escape a string literal or append a new clause.
_SAFE_LITERAL = re.compile(r"^[A-Za-z0-9_.@:/+-]{1,128}$")


class SqlValueError(ValueError):
    """A caller-supplied value is not safe to place in a SQL statement."""


def _token(rendered: str) -> str:
    """Parenthesise a negative numeric token so it cannot fuse with a preceding operator.

    `x - {token}` with token '-5' renders `x --5`, and `--` starts a line comment that
    swallows the rest of a single-line query. Today only the space in the f-string keeps
    them apart, which is a formatting accident rather than an invariant. Positive tokens
    are left bare: BigQuery's LIMIT takes a literal, not a parenthesised expression.
    """
    return f"({rendered})" if rendered.startswith("-") else rendered


def normalize_literal(value: str, *, name: str) -> str:
    """Return the validated, whitespace-stripped value, or raise.

    Callers that also use the value outside SQL — a `"gene": gene` echo field, a
    `filename=f"{gene}_mpra.tsv"` download name that ends up in a Content-Disposition
    header — must use this form rather than the raw argument. Validation runs on the
    stripped value, so the raw one can still carry leading/trailing CR/LF that the
    allow-list never saw.
    """
    if not isinstance(value, str):
        raise SqlValueError(f"{name} must be a string, got {type(value).__name__}")
    stripped = value.strip()
    if not _SAFE_LITERAL.match(stripped):
        raise SqlValueError(
            f"invalid {name}: {value!r}. Only letters, digits and _ . @ : / + - "
            f"are allowed (max 128 characters)."
        )
    return stripped


def quote_literal(value: str, *, name: str) -> str:
    """Return `value` as a single-quoted BigQuery string literal, or raise.

    Raises SqlValueError unless the value matches the allow-list, which is why the result
    can be interpolated: nothing that survives validation can close the quote.
    """
    return f"'{normalize_literal(value, name=name)}'"


def quote_literal_list(values, *, name: str) -> str:
    """Return a comma-separated list of quoted literals for an IN (...) clause."""
    items = list(values)
    if not items:
        raise SqlValueError(f"{name} must not be empty")
    return ", ".join(quote_literal(v, name=name) for v in items)


def sql_int(value, *, name: str, minimum: int | None = None, maximum: int | None = None) -> str:
    """Return `value` as a SQL integer token, or raise.

    A token, not a round-trippable number: `_token` parenthesises negatives, so
    `int(sql_int(-5, name="x"))` raises a bare ValueError. Five `*_by_gene` tools in
    tools/executor.py do re-parse this return value to recover the clamped limit, and
    they are safe only because every one of them passes `minimum=1`. Dropping that floor
    — or adding a re-parsing call site that permits negatives — lets the ValueError past
    their `except SqlValueError` handlers, which do not catch it, so the tool raises
    instead of returning {"success": False, ...}.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise SqlValueError(f"{name} must be a number, got {type(value).__name__}")
    if isinstance(value, float) and not float(value).is_integer():
        raise SqlValueError(f"{name} must be a whole number, got {value!r}")
    number = int(value)
    if minimum is not None and number < minimum:
        raise SqlValueError(f"{name} must be >= {minimum}, got {number}")
    if maximum is not None and number > maximum:
        raise SqlValueError(f"{name} must be <= {maximum}, got {number}")
    return _token(str(number))


def sql_float(
    value, *, name: str, minimum: float | None = None, maximum: float | None = None
) -> str:
    """Return `value` as a SQL float token, or raise."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise SqlValueError(f"{name} must be a number, got {type(value).__name__}")
    number = float(value)
    if not math.isfinite(number):
        raise SqlValueError(f"{name} must be a finite number, got {value!r}")
    if minimum is not None and number < minimum:
        raise SqlValueError(f"{name} must be >= {minimum}, got {number}")
    if maximum is not None and number > maximum:
        raise SqlValueError(f"{name} must be <= {maximum}, got {number}")
    return _token(repr(number))
